CREATE DATABASE QLQTT
GO
USE QLQTT


-----------------------------------B1: THANHVIENCHINHTHUC-------------------------------------
CREATE FUNCTION AUTO_IDTV()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdTV) FROM THANHVIENCHINHTHUC) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdTV, 4)) FROM THANHVIENCHINHTHUC
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TV000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'TV00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'TV0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'TV'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE THANHVIENCHINHTHUC
(
	IdTV CHAR(6) PRIMARY KEY CONSTRAINT IdTV DEFAULT DBO.AUTO_IDTV(),
	TenTV NVARCHAR(60) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	Email CHAR(50),
	DiaChi nvarchar(200) NOT NULL, 
	CMND int,
	NThamGia smalldatetime,
)
-- chuyen doi ngay thang --
SET DATEFORMAT DMY
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Huỳnh Uy Dũng', '0957475845', 'huydung698@gmail.com',N'Bình Dương', '123456788','2/10/2015')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Huỳnh Hằng Hữu', '0957475895', 'hanghuu698@gmail.com',N'Bình Dương', '123456789','23/4/2014')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Nguyễn Phương HẰng ', '0957736453', 'phuonghang698@gmail.com',N'Bình Dương', '123456789','3/4/2016')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Dương Thanh Phi', '0957736453', 'thanhphi698@gmail.com',N'Bình Dương', '123456789','3/4/2016')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Nguyễn Tuấn Khang', '0957732856', 'tuankhang698@gmail.com',N'Tân Phú', '123456789','4/6/2016')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Nguyễn Văn An', '0906762255', 'nguyenan698@gmail.com', N'THỦ ĐỨC', '123456789','29/11/2014')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Phan Tấn Đạt', '0975672350', 'tuandat698@gmail.com',N'QUẬN 1', '123456789','25/4/2015')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Nguyễn Anh Hải', '0947578688', 'nguyenanh698@gmail.com',N'QUẬN 9', '123456789','3/5/2017')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Phạm Tài', '0956757869', 'phamtai698@gmail.com',N'QUẬN 1', '123456789','30/3/2017')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Lê Thúy Hằng', '0976668688', 'thuyhang698@gmail.com',N'QUẬN 3', '123456789','4/6/2018')
INSERT INTO THANHVIENCHINHTHUC( TenTV, SDT, Email, DiaChi, CMND , NThamGia ) VALUES
( N'Ưng Hồng Ân', '0957475898', 'hongan698@gmail.com',N'Tân Phú', '123456789','25/9/2021')



-----------------------------------B2: HOIDONGDIEUHANH-------------------------------------
CREATE FUNCTION AUTO_IDCV()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdCV) FROM HOIDONGDIEUHANH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdCV, 4)) FROM HOIDONGDIEUHANH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CV000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'CV00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'CV0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'CV'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE HOIDONGDIEUHANH
(
	IdCV CHAR(6) PRIMARY KEY CONSTRAINT IdCV DEFAULT DBO.AUTO_IDCV(),
	TenCV NVARCHAR(50) NOT NULL,
	NNhanChuc smalldatetime NOT NULL,
	IdTV CHAR(6) NOT NULL  FOREIGN KEY REFERENCES THANHVIENCHINHTHUC(IdTV),	
)

INSERT INTO HOIDONGDIEUHANH( TenCV, NNhanChuc, idTV) VALUES
( N'Chủ Tịch HDQT', '2016-10-02', 'TV0001')
INSERT INTO HOIDONGDIEUHANH( TenCV, NNhanChuc, idTV) VALUES
( N'Tổng Giám Đốc', '2017-10-02', 'TV0002')
INSERT INTO HOIDONGDIEUHANH( TenCV, NNhanChuc, idTV) VALUES
( N'Phó Giám Đốc', '2016-06-03', 'TV0003')
INSERT INTO HOIDONGDIEUHANH( TenCV, NNhanChuc, idTV) VALUES
( N'Giám Đốc Điều Hành', '2016-07-03', 'TV0004')

-----------------------------------B3: NHA HAO TAM-------------------------------------
CREATE FUNCTION AUTO_IDHT()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdNHT) FROM NHAHAOTAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdNHT, 4)) FROM NHAHAOTAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HT000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'HT00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'HT0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'HT0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE NHAHAOTAM
(
	IdNHT CHAR(6) PRIMARY KEY CONSTRAINT IdNHT DEFAULT DBO.AUTO_IDHT(),
	TenNHT NVARCHAR(50) ,
	PhapDanh NVARCHAR(30) ,
	SDT VARCHAR(10) NOT NULL,
	DiaChi CHAR(200),	
)


INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Tran Ngoc Han','tranngoc', '0908256478',N'23/5 Nguyen Trai, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Nguyen Thi Huyen Linh','huyenlinh', '0908253478',N'731 Tran Hung Dao, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Dang Thi ngoc','dangngoc', '0908256678',N'23/5 Nguyen Trai, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'luu Thai Dung','thaidung', '0908256434',N'45 Nguyen Canh Chan, Q1, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Dinh Thi Diem Suong','tranngoc', '0978256478',N'50/34 Le Dai Hanh, Q10, TpHCM, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Nguyen Ngoc Lan','ngoclan', '0994667948',N'34 Truong Dinh, Q3, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Nguyen Xuan Quan','Xuan Quan', '0908256478',N'23/5 Nguyen Trai, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Bui Phuong Linh','phuoonglinh', '0908259275',N'227 Nguyen Van Cu, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'Hoi tu thien Minh Tam','minhtam', '0984539988',N'32/3 Tran Binh Trong, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'To Chuc Tam Nhin The Gioi','World Vision', '0908256478',N'873 Le Hong Phong, Q5, TpHCM')
INSERT INTO NHAHAOTAM( TenNHT, PhapDanh, SDT, DiaChi ) VALUES
( N'To Chuc Phau Thuat Nu Cuoi','Operation Smilec', '0437644837',N'34/34B Nguyen Trai, Q1, TpHCM')

-----------------------------------B4: DOI TUONG HUONG THU------------------------------------
CREATE FUNCTION AUTO_IDTH()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdDTHT) FROM DOITUONGHUONGTHU) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdDTHT , 4)) FROM DOITUONGHUONGTHU
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TH000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'TH00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'TH0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'TH'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE DOITUONGHUONGTHU
(
	IdDTHT CHAR(6) PRIMARY KEY CONSTRAINT IdDTHT DEFAULT DBO.AUTO_IDTH(),
	TenDTHT NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	Email CHAR(50),
	DiaChi nvarchar(200) NOT NULL, 
	HoanCanh nvarchar(500) NOT NULL,
)
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Tran Ngoc Han','0987567390', 'ngochan@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Mồ Côi')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Bao ha','0987546790', 'baohan@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Thuong Binh')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Tu Duy Khanh','0987568475', 'duykhanh@gmail.com',N'23/5 Nguyen Trai, Q5, TpHCM', N'Lu Lut')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Nguyen Ly Vy Tuyen','0987837465', 'vytuyen@gmail.com',N'45 Nguyen Canh Chan, Q1, TpHCM', N'Benh hiem ngheo')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'phuc Khai Nguyen','0987567374', 'khainguyen@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Dich Benh')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'tran Thi Diem Mi','0987565990', 'diemmi@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Benh hiem ngheo')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Nguyen Hieu nghia','0987569390', 'hieunghia@gmail.com',N'873 Le Hong Phong, Q5, TpHCM', N'Mồ Côi')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Dieu Phuong Phuong','098750390', 'phuongphuong@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Benh hiem ngheo')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Nguyen Thi Nhu Y','0987567087', 'nhuy@gmail.com',N'873 Le Hong Phong, Q5, TpHCM', N'Mồ Côi')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Duong Kieu Ngoc Han','0987567650', 'ngochan@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Benh hiem ngheo')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Nguyen Thi Thuy Kieu','0987567982', 'thuykieu@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Mồ Côi')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Nguyen Hung Thinh','0987503850', 'hungthing@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'Thuong Binh')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Quỹ Từ Thiện Tâm Anh','0987585746', 'quocviet@gmail.com',N'873 Le Hong Phong, Q5, TpHCM', N'Thuong Binh')
INSERT INTO DOITUONGHUONGTHU( TenDTHT, SDT, Email, DiaChi,HoanCanh  ) VALUES
( N'Cô Nhi Viện Hạnh Nhi','0987567984', 'xuandang@gmail.com',N'34/34B Nguyen Trai, Q1, TpHCM', N'lu lut men trung')



-----------------------------------B5: TINH NGUYEN VIEN------------------------------------
CREATE FUNCTION AUTO_IDTNV()
RETURNS VARCHAR(7)
AS
BEGIN
	DECLARE @ID VARCHAR(7)
	IF (SELECT COUNT(IdTNV) FROM TINHNGUYENVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdTNV , 4)) FROM TINHNGUYENVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TNV000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'TNV00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'TNV0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'TNV'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE TINHNGUYENVIEN
(
	IdTNV VARCHAR(7)  PRIMARY KEY CONSTRAINT IdTNV DEFAULT DBO.AUTO_IDTNV(),
	TenTNV NVARCHAR(50) ,
	SDT VARCHAR(10) NOT NULL,
	Email CHAR(50),

)

INSERT INTO TINHNGUYENVIEN( TenTNV, SDT, Email  ) VALUES
( N'Nguyen Thi Tra Mi','0987847984', 'trami@gmail.com')
INSERT INTO TINHNGUYENVIEN( TenTNV, SDT, Email  ) VALUES
( N'Tran Nha Ca','0987847984', 'nhaca@gmail.com')
INSERT INTO TINHNGUYENVIEN( TenTNV, SDT, Email ) VALUES
( N'Tran Thien Thanh','0987847384', 'thienthach@gmail.com')
INSERT INTO TINHNGUYENVIEN( TenTNV, SDT, Email ) VALUES
( N'Tien Trong Dong','0987847984', 'trami@gmail.com')
INSERT INTO TINHNGUYENVIEN( TenTNV, SDT, Email ) VALUES
( N'Nguyen Minh Phung','0987847765', 'minhphung@gmail.com')


-----------------------------------B6: DU AN TU THIEN------------------------------------
CREATE FUNCTION AUTO_IDDATT()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdDA) FROM DUANTUTHIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdDA , 4)) FROM DUANTUTHIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'DA000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'DA00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'DA0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'DA'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE DUANTUTHIEN
(
	IdDA CHAR(6)  PRIMARY KEY CONSTRAINT IdDA DEFAULT DBO.AUTO_IDDATT(),
	TenDA NVARCHAR(100) NOT NULL,
	ThoiGianBD smalldatetime NOT NULL,
	ThoiGianKT smalldatetime NOT NULL,
	IdTV CHAR(6) NOT NULL FOREIGN KEY REFERENCES THANHVIENCHINHTHUC(IdTV)
	
)
INSERT INTO DUANTUTHIEN( TenDA, ThoiGianBD,ThoiGianKT, IdTV) VALUES
( N'Suất Ăn Giá Rẻ', '2/10/2017', '2/10/2022', 'TV0005')
INSERT INTO DUANTUTHIEN( TenDA, ThoiGianBD,ThoiGianKT, IdTV) VALUES
( N'Trợ Giúp Y  Tế', '2/10/2013', '2/10/2025', 'TV0006')
INSERT INTO DUANTUTHIEN( TenDA, ThoiGianBD,ThoiGianKT, IdTV) VALUES
( N'Hỗ Trợ Giáo Giục', '2/10/2020', '2/10/2022', 'TV0001')
INSERT INTO DUANTUTHIEN( TenDA, ThoiGianBD,ThoiGianKT, IdTV) VALUES
( N'Xay Dung', '2/10/2017', '2/10/2021', 'TV0001')



-----------------------------------B7: NOI TIEP NHAN TU THIEN------------------------------------
CREATE FUNCTION AUTO_IDNTN1()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdNTN) FROM NOITIEPNHAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdNTN , 4)) FROM NOITIEPNHAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'DD000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'DD00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'DD0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'DD'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE NOITIEPNHAN  
(
	IdNTN CHAR(6)PRIMARY KEY CONSTRAINT IdNTN DEFAULT DBO.AUTO_IDNTN1(),
	DiaChi nvarchar(200) NOT NULL,
	NguoiLienhe NVARCHAR(100) NOT NULL,
	GioTiepNhan nvarchar(200) NOT NULL,
)

INSERT INTO NOITIEPNHAN( DiaChi, NguoiLienhe, GioTiepNhan) VALUES
( N'Lầu 5, Tòa nhà Huy Sơn, Số 11 Mai Thị Lựu P. Đa Kao Q.1 Tp.HCM', N'Ms. Ngọc Phương(0909.609.385) hoặc Ms. Nhã Trúc(0966.909.403)', N'8h15 – 17h (T2-T6)')
INSERT INTO NOITIEPNHAN( DiaChi, NguoiLienhe, GioTiepNhan) VALUES
( N'Số 596 Trần Hưng Đạo, P.14, Q.5', N'Ms. Lanh(0981873723)', N'8h15 – 16h (T2-T7)')
INSERT INTO NOITIEPNHAN( DiaChi, NguoiLienhe, GioTiepNhan) VALUES
( N'Số 170 Tân Sơn Nhì, P.Tân Sơn Nhì, Q.Tân Phú', N'Ms. Thu Vân (0348.652.508)', N'8h15 – 16h (T2-T7)')
INSERT INTO NOITIEPNHAN( DiaChi, NguoiLienhe, GioTiepNhan) VALUES
( N'68 Lý Triện, An Khê, Thanh Khê, Đà Nẵng', N'Ms. Nguyệt(038.2578.363)hoặc Ms Vân Khánh (090.551.6609)', N'8h15 – 16h (T2-T7)')
INSERT INTO NOITIEPNHAN( DiaChi, NguoiLienhe, GioTiepNhan) VALUES
( N'Số 136 ngõ 88 Trần Quý Cáp, P. Văn Chương, Q. Đống Đa, Hà Nội', N'Mr. Sơn (097 207 1234)', N'8h15 – 16h (T3–T5-T7)')

-----------------------------------B8: TAI KHOAN TIEP NHAN------------------------------------

CREATE TABLE TAIKHOANTIEPNHAN 
(
	SoTK VARCHAR(20) PRIMARY KEY,
	TenTK NVARCHAR(100) NOT NULL,
	NganHang NVARCHAR(200) NOT NULL
)
INSERT INTO TAIKHOANTIEPNHAN( SoTK, TenTK, NganHang) VALUES
('221080689000084', N'Quỹ Từ thiện Bông Sen', N'Ngân Hàng Thương Mại Cổ Phần Xuất Nhập Khẩu Việt Nam (EXIMBANK) – Phòng giao dịch Đa Kao')
INSERT INTO TAIKHOANTIEPNHAN( SoTK, TenTK, NganHang) VALUES
('508398', N'Quỹ Từ thiện Bông Sen', N'Ngân hàng thương mại cổ phần Á Châu (ACB) – Chi nhánh Sài Gòn')



-----------------------------------B9: DONG GOP TRUC TIEP------------------------------------

CREATE FUNCTION AUTO_IDPTTT()
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @ID VARCHAR(8)
	IF (SELECT COUNT(MaPTTT) FROM DGTRUCTIEP) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPTTT , 4)) FROM DGTRUCTIEP
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PTTT000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'PTTT00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'PTTT0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'PTTT'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE DGTRUCTIEP
(
	MaPTTT CHAR(8)PRIMARY KEY CONSTRAINT MaPTTT DEFAULT DBO.AUTO_IDPTTT(),
	Ngay smalldatetime NOT NULL,
	TriGia Money,
	HienVat nvarchar(200) ,
	IdNHT CHAR(6) NOT NULL  FOREIGN KEY REFERENCES NHAHAOTAM(IdNHT),
	IdNTN CHAR(6) NOT NULL FOREIGN KEY REFERENCES NOITIEPNHAN(IdNTN),
	IdDA CHAR(6) NOT NULL FOREIGN KEY REFERENCES DUANTUTHIEN(IdDA)
)
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('26-12-2029','2000','52kg Chả cá','HT0001','DD0001','DA0001')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('25-10-2018','10000','','HT0002','DD0002','DA0002')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('24-9-2018','2000','01 bao quần áo ấm','HT0003','DD0003','DA0003')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('23-8-2020','','01 bao quần áo trẻ em; 01 thùng sách, truyện','HT0004','DD0004','DA0004')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('22-7-2021','55','5kg đùi gà','HT0005','DD0005','DA0003')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('21-6-2019','15000','','HT0006','DD0001','DA0001')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('19-5-2018','','Mì tôm 1 thùng (100 gói)','HT0007','DD0002','DA0001')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('18-4-2020','999','','HT0008','DD0003','DA0002')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('18-3-2018','','Nước mắm Liên Thành (48c x 500ml)','HT0009','DD0004','DA0003')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('16-2-2020','800','04 nải chuối già hương','HT0010','DD0005','DA0004')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('1-1-2021','','Khoai tây 10kg, Khoai mỡ 5kg, Su su 5kg, Bí xanh 4kg, Cà tím 4kg, Bí đỏ 9kg','HT0011','DD0001','DA0003')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('2-2-2021','4000','','HT0001','DD0002','DA0002')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('3-3-2020','50','Cá biển con thập cẩm 20 kg','HT0002','DD0003','DA0001')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('4-4-2018','10000','','HT0003','DD0004','DA0002')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('5-5-2019','2000','Đường 5 kg +Muối 5 kg','HT0004','DD0005','DA0003')
INSERT INTO DGTRUCTIEP( Ngay, TriGia, HienVat, IdNHT,IdNTN, IdDA ) VALUES
('6-6-2020','200','540 quả trứng gà so','HT0006','DD0001','DA0004')



-----------------------------------B10: DONG GOP ONLINE------------------------------------
CREATE FUNCTION AUTO_IDPTOL()
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @ID VARCHAR(8)
	IF (SELECT COUNT(MaPTOL) FROM DGONLINE) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPTOL , 4)) FROM DGONLINE
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PTOL000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'PTOL00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'PTOL0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'PTOL'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE DGONLINE   
(
	MaPTOL CHAR(8)PRIMARY KEY CONSTRAINT MaPTOL DEFAULT DBO.AUTO_IDPTOL(),
	Ngay smalldatetime NOT NULL,
	TriGia Money NOT NULL,
	IdNHT CHAR(6) NOT NULL  FOREIGN KEY REFERENCES NHAHAOTAM(IdNHT),
	SoTK  VARCHAR(20)   NOT NULL FOREIGN KEY REFERENCES TAIKHOANTIEPNHAN(SoTK),
	IdDA CHAR(6)  NOT NULL FOREIGN KEY REFERENCES DUANTUTHIEN(IdDA)
)
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('26-11-2021','7000','HT0001','221080689000084','DA0001')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('23-11-2020','400','HT0002','508398','DA0002')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('21-10-2019','200','HT0003','221080689000084','DA0003')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('22-9-2028','50','HT0004','508398','DA0004')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('20-3-2020','300','HT0009','221080689000084','DA000')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('21-9-2021','11000','HT0010','508398','DA0003')
INSERT INTO DGONLINE (Ngay, TriGia, IdNHT,SoTK, IdDA ) VALUES
('19-4-2019','20000','HT0010','508398','DA0001')




-----------------------------------B11: SU KIEN------------------------------------
CREATE FUNCTION AUTO_IDSK()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(IdSK) FROM SUKIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(IdSK , 4)) FROM SUKIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SK000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'SK00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'SK0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'SK'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE SUKIEN 
(
	IdSK CHAR(6) PRIMARY KEY CONSTRAINT IdSK DEFAULT DBO.AUTO_IDSK(),
	TenSK NVARCHAR(100) NOT NULL,
	MucDich NVARCHAR(500),
	DiaDiem nvarchar(200) NOT NULL, 
	ThoiGianBD smalldatetime NOT NULL,
	ThoiGianKT smalldatetime NOT NULL,
	IdDA CHAR(6) NOT NULL FOREIGN KEY REFERENCES DUANTUTHIEN(IdDA)	
)
INSERT INTO SUKIEN (TenSK, MucDich,DiaDiem, ThoiGianBD,ThoiGianKT, IdDA) VALUES
(N'Cơ từ thiện sinh viên',N'Tặng Xuất Cơm Từ Thiện Cho Sinh Viên Mắc Kẹt Tại Vùng Dịch',N'Làng Đại Học','11-10-2021','15-10-2021','DA0001')

INSERT INTO SUKIEN (TenSK, MucDich,DiaDiem, ThoiGianBD,ThoiGianKT, IdDA) VALUES
(N'Xây dựng khu vui chơi',N'Xây dựng khu vui chơi cho cô nhi viện',N'Làng Đại Học','1-1-2021','6-6-2021','DA0004')

-----------------------------------B12: TINH NGUYEN VIEN SU KIEN------------------------------------

CREATE TABLE TNV_SK
(
	IdTNV VARCHAR(7) FOREIGN KEY REFERENCES TINHNGUYENVIEN(IdTNV)	 ,
	IdSK CHAR(6) FOREIGN KEY REFERENCES SUKIEN(IdSK)	 ,
	NgayTG smalldatetime NOT NULL,
	PRIMARY KEY (IdTNV, IdSK,NgayTG)
)
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0001','SK0001','11-10-2021')
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0003','SK0001','12-10-2021')
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0004','SK0002','23-4-2021')
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0002','SK0001','13-10-2021')
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0005','SK0002','5-4-2021')
INSERT INTO TNV_SK (IdTNV, IdSK,NgayTG) VALUES
('TNV0005','SK0001','15-10-2021')

-----------------------------------B13: THANH VIEN CHINH THUC VA DU AN------------------------------------
CREATE TABLE TVHT_DATT  
(	IdDA CHAR(6) FOREIGN KEY REFERENCES DUANTUTHIEN(IdDA),	
	IdTV CHAR(6) FOREIGN KEY REFERENCES THANHVIENCHINHTHUC(IdTV),
	PRIMARY KEY (IdDA, IdTV)
)
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0001','TV0001')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0002','TV0002')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0003','TV0003')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0004','TV0004')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0001','TV0005')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0003','TV0006')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0004','TV0007')
INSERT INTO TVHT_DATT (IdDA, IdTV) VALUES
('DA0002','TV0008')
-----------------------------------B14: PHI CHI PHAT SINH------------------------------------
CREATE FUNCTION AUTO_IDPHIPHATSINH ()
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @ID VARCHAR(8)
	IF (SELECT COUNT(MaPCPS) FROM PHIPHATSINH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPCPS , 4)) FROM PHIPHATSINH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PCPS000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'PCPS00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'PCPS0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'PCPS'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE PHIPHATSINH   
(	MaPCPS CHAR(8) PRIMARY KEY CONSTRAINT MaPCPS DEFAULT DBO.AUTO_IDPHIPHATSINH(),
	Ngay smalldatetime NOT NULL,
	DienGiai NVARCHAR(500)  NOT NULL,
	TriGia Money  NOT NULL,
	IdTV CHAR(6)NOT NULL FOREIGN KEY REFERENCES THANHVIENCHINHTHUC(IdTV),
)
INSERT INTO PHIPHATSINH (Ngay, DienGiai,TriGia,IdTV) VALUES
('13-10-2021',N'trả thuê thêm nhân viên','10000', 'TV0002')
INSERT INTO PHIPHATSINH (Ngay, DienGiai,TriGia,IdTV) VALUES
('1-1-2021',N'Thuê xe chở đồ','200','TV0001')
INSERT INTO PHIPHATSINH (Ngay, DienGiai,TriGia,IdTV) VALUES
('4-3-2020',N'Phí trả tiền điện hặng tháng','500','TV0004')
INSERT INTO PHIPHATSINH (Ngay, DienGiai,TriGia,IdTV) VALUES
('13-10-2021',N'Thuê mặt bằng làm việc','500', 'TV0002')


-----------------------------------B15: PHI CHI QUYEN GOP-----------------------------------
CREATE FUNCTION AUTO_IDPHIQUYENGOP ()
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @ID VARCHAR(8)
	IF (SELECT COUNT(MaPCQG) FROM PHIQUYENGOP) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPCQG , 4)) FROM PHIQUYENGOP
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PCQG000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  and @ID < 99 THEN  'PCQG00'+ CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999  THEN  'PCQG0'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
			WHEN @ID >= 999  THEN  'PCQG'+ CONVERT(CHAR, CONVERT(CHAR, @ID) + 1)
		END
	RETURN @ID
END

CREATE TABLE PHIQUYENGOP    
(	MaPCQG CHAR(8)  PRIMARY KEY CONSTRAINT MaPCQG DEFAULT DBO.AUTO_IDPHIQUYENGOP(),
	Ngay smalldatetime NOT NULL,
	DienGiai NVARCHAR(500) NOT NULL,
	TriGia Money,
	IdDA CHAR(6) NOT NULL FOREIGN KEY REFERENCES DUANTUTHIEN(IdDA),
	IdTV CHAR(6) NOT NULL FOREIGN KEY REFERENCES THANHVIENCHINHTHUC(IdTV),
	IdDTHT CHAR(6)  FOREIGN KEY REFERENCES DOITUONGHUONGTHU(IdDTHT),
)

INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('13-10-2021',N'Hỗ trợ tiền ăn và một xuất cơm miễn phí cho sinh viên mắc kệt vùng dịch','200','DA0001','TV0001','TH0001')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('13-10-2021',N'Hỗ trợ tiền ăn và một xuất cơm miễn phí cho sinh viên mắc kệt vùng dịch','200','DA0001','TV0001','TH0002')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('13-10-2021',N'Hỗ trợ tiền ăn và một xuất cơm miễn phí cho sinh viên mắc kệt vùng dịch','200','DA0001','TV0001','TH0003')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('13-10-2021',N'Hỗ trợ tiền ăn và một xuất cơm miễn phí cho sinh viên mắc kệt vùng dịch','200','DA0001','TV0001','TH0004')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('13-10-2021',N'Hỗ trợ tiền ăn và một xuất cơm miễn phí cho sinh viên mắc kệt vùng dịch','200','DA0001','TV0001','TH0004')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('12-3-2019',N'Học bổng học sinh nghèo vượt khó','500','DA0003','TV0005', 'TH0006')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('12-3-2020',N'Ủng hộ cho cô nhi viện đợt 1 ','10000','DA0003','TV0005','TH0014')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('12-3-2020',N'50 cuốn truyệ tranh, 200kg gạo, 10kg dầu ăn','','DA0003','TV0005','TH0014')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV,IdDTHT) VALUES
('4-6-2020',N'Ủng hộ quỹ từ thiện tâm anh đợt 1 ','1000','DA0003','TV0005','TH0013')
INSERT INTO PHIQUYENGOP (Ngay, DienGiai,TriGia,IdDA,IdTV) VALUES
('4-6-2020',N'Trích 30kg gạo để nấu cơm từ thiện','','DA0001','TV0005')




---------------------------------TẠO CÁC RẰNG BUỘC BẰNG TRIGGER-------------------------------------
----1: Ngày bắt đâu dự án phải nhỏ hơn ngày kết thúc dự á
CREATE TRIGGER DATT_NBD_NKT ON DUANTUTHIEN
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 
		WHERE D1.ThoiGianBD > D1.ThoiGianKT)>0
	BEGIN 
		PRINT 'ERROR: NGBD PHAI < NKT' 
		ROLLBACK TRAN
	END
END
----2: ngày bắt đầu sự kiện phải lớn hơn ngày kết thúc sự kiện
CREATE TRIGGER SK_NBD_NKT ON SUKIEN
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 
		WHERE D1.ThoiGianBD > D1.ThoiGianKT)>0
	BEGIN 
		PRINT 'ERROR: NGBD PHAI < NKT' 
		ROLLBACK TRAN
	END
END
SELECT *
FROM DGTRUCTIEP

----3: Đóng góp trực tiếp không được để trống cả 2 thuộc tính hiện vật và giá trị
CREATE TRIGGER QG_DGTT ON DGTRUCTIEP
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 
		WHERE D1.HienVat='' AND  D1.TriGia='')>0
	BEGIN 
		PRINT 'ERROR: DONG GOP TRUC TIEP KHONG DUOC BO TRONG HIEN VAT VA TRI GIA' 
		ROLLBACK TRAN
	END
END

----4: Ngày của tất cả các thuộc tính liên quan đến dự án phải lớn hơn ngày bắt đầu và nhỏ hơn ngày kết thúc của dự án từ thiện đó
---DGTRUCTIEP
CREATE TRIGGER NGAY_DA_DGTT ON DGTRUCTIEP
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay < D2.ThoiGianBD)>0
		BEGIN 
			PRINT 'ERROR: NGAY DONG GOP PHAI LON HON NGAY BAT DAU DU AN' 
			ROLLBACK TRAN
		END
	ELSE IF(SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay > D2.ThoiGianKT)>0
		BEGIN 
			PRINT 'ERROR: NGAY DONG GOP PHAI NHO HON NGAY KET THUC DU AN' 
			ROLLBACK TRAN
		END
END
---DGONLINE   
CREATE TRIGGER NGAY_DA_DGOL ON DGONLINE 
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay < D2.ThoiGianBD)>0
		BEGIN 
			PRINT 'ERROR: NGAY DONG GOP PHAI LON HON NGAY BAT DAU DU AN' 
			ROLLBACK TRAN
		END
	ELSE IF(SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay > D2.ThoiGianKT)>0
		BEGIN 
			PRINT 'ERROR: NGAY DONG GOP PHAI NHO HON NGAY KET THUC DU AN' 
			ROLLBACK TRAN
		END
END
---SUKIEN
CREATE TRIGGER NGAY_DA_SK ON DGONLINE 
FOR INSERT , UPDATE 
AS 
BEGIN
	IF(	SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay < D2.ThoiGianBD)>0
		BEGIN 
			PRINT 'ERROR: NGAY BAT DAU SU KIEN PHAI LON HON NGAY BAT KET BAT DAU DU AN ' 
			ROLLBACK TRAN
		END
	ELSE IF(SELECT COUNT(*) 
		FROM INSERTED D1 , DUANTUTHIEN D2
		WHERE D1.Ngay > D2.ThoiGianKT)>0
		BEGIN 
			PRINT 'ERROR: NGAY BAT DAU SU KIEN PHAI NHO HON NGAY KET THUC SU KIEN' 
			ROLLBACK TRAN
		END
END

----5: mỗi thành viên chính thức chỉ được quản lý một dự án duy nhất

CREATE TRIGGER DA_TVQL ON THANHVIENCHINHTHUC
FOR INSERT , UPDATE 
AS 
BEGIN
	DECLARE @DTB  VARCHAR(6)
	SET @DTB = (SELECT D1.IdTV
				FROM INSERTED D1, DUANTUTHIEN D2
				WHERE D1.IdTV = D2.IdTV )
	IF(@DTB='')
	BEGIN 
		PRINT 'ERROR: NHAN VIEN NAY DA QUAN LY DU AN ' +@DTB
		ROLLBACK TRAN
	END
END
---------------------------------PHÂN QUYỀN CHO CƠ SỞ DỮ LIỆU-------------------------------------
--KHOI TAO 6 USER
CREATE LOGIN L1 with password ='123456'
CREATE USER [tonggiamdoc] FOR LOGIN [L1]
CREATE LOGIN L2 with password ='123456'
CREATE USER [phogiamdoc] FOR LOGIN [L2]
CREATE LOGIN L3 with password ='123456'
CREATE USER [phogiamdoc] FOR LOGIN [L4]
CREATE LOGIN L4 with password ='123456'
CREATE USER [nhanvien1] FOR LOGIN [L5]
CREATE LOGIN L5 with password ='123456'
CREATE USER [nhanvien2] FOR LOGIN [L5]
CREATE LOGIN L6 with password ='123456'
CREATE USER [other] FOR LOGIN [L6]
--TAO 3 ROLE 
CREATE ROLE Quantri
CREATE ROLE NhanVien
CREATE ROLE NguoiDung
-- TAO NHÓM: [tonggiamdoc][phogiamdoc][chutichhoidong] thuộc Quantri/ [nhanvien1][nhanvien2] Thuộc NhanVien/ [other] thuoc người dùng
EXEC sp_addrolemember Quantri, tonggiamdoc
EXEC sp_addrolemember Quantri, phogiamdoc
EXEC sp_addrolemember Quantri, phogiamdoc
EXEC sp_addrolemember NhanVien, nhanvien1
EXEC sp_addrolemember NhanVien, nhanvien2
EXEC sp_addrolemember NguoiDung, other
-- CẤP QUYỀN 

GRANT SELECT, INSERT,  DELECT , UPDATE ON TAIKHOANTIEPNHAN TO tonggiamdoc
GRANT SELECT, INSERT,  DELECT , UPDATE ON TAIKHOANTIEPNHAN TO phogiamdoc
DENY INSERT, UPDATE,DELECT ON DGONLINE TO NguoiDung
DENY INSERT, UPDATE,DELECT ON DGTRUCTIEP TO NguoiDung


---------------------------------CHỨC NĂNG TỪ BẢNG ĐÃ LÀM -------------------------------------
-----CN1: Tạo Báo cáo thu chi cho từng dự án 
---BÁO CÁO NGÂN SÁCH CỦA TỪNG DỰ ÁN 
CREATE FUNCTION BAOCAONGANSACHTUNGDUAN(@IdDA VARCHAR (6))
RETURNS @new_table TABLE (TONG MONEY, DACHI MONEY, CONDU MONEY )
AS 
BEGIN
	DECLARE @TONG MONEY
	DECLARE @DACHI MONEY
	DECLARE @CONDU MONEY
	SET @TONG =0 
	SET @DACHI =0 
	SET @CONDU =0 
	IF(EXISTS (SELECT* FROM DUANTUTHIEN WHERE IdDA=@IdDA))
	BEGIN 
		
		IF( EXISTS (SELECT * FROM DGONLINE WHERE IdDA=@IdDA))
			BEGIN
				SELECT @TONG=SUM(TriGia) +@TONG
				FROM DGONLINE
				WHERE IdDA=@IdDA
			END
		IF( EXISTS (SELECT * FROM DGTRUCTIEP WHERE IdDA=@IdDA))
			BEGIN
				SELECT @TONG=SUM(TriGia) +@TONG
				FROM DGTRUCTIEP
				WHERE IdDA=@IdDA
			END
		IF( EXISTS (SELECT * FROM PHIQUYENGOP WHERE IdDA=@IdDA))
		BEGIN
			SELECT @DACHI=SUM(TriGia) + @DACHI
			FROM PHIQUYENGOP
			WHERE IdDA=@IdDA
		END
		SET @CONDU = @TONG- @DACHI
		
	END
	INSERT INTO @new_table VALUES (@TONG, @DACHI,@CONDU )
	RETURN 
END
SELECT *FROM BAOCAONGANSACHTUNGDUAN('DA0004') d1 
---BÁO CÁO NGÂN SÁCH CỦA TAI CA DU AN

CREATE FUNCTION BAOCAONGANTATCA()
RETURNS @new_table TABLE (IdDUAN VARCHAR(6),TONG MONEY, DACHI MONEY, CONDU MONEY )
AS
BEGIN
	DECLARE @TONG MONEY
	DECLARE @DACHI MONEY
	DECLARE @CONDU MONEY
	DECLARE @IdDUAN VARCHAR(6)
	
	DECLARE cursorIDDA CURSOR FOR
	SELECT d1.IdDA FROM DUANTUTHIEN d1
	Open cursorIDDA

	FETCH NEXT FROM cursorIDDA into @IdDUAN

	WHILE @@FETCH_STATUS = 0 
		BEGIN
			SET @TONG = (SELECT d1.TONG FROM BAOCAONGANSACHTUNGDUAN(@IdDUAN) d1)
			SET @DACHI= (SELECT d2.DACHI FROM BAOCAONGANSACHTUNGDUAN(@IdDUAN) d2)
			SET @CONDU= (SELECT d3.CONDU FROM BAOCAONGANSACHTUNGDUAN(@IdDUAN) d3)

			INSERT INTO @new_table VALUES ( @IdDUAN, @TONG, @DACHI,@CONDU )	
			FETCH NEXT FROM cursorIDDA into @IdDUAN
		END
	CLOSE cursorIDDA   
	DEALLOCATE cursorIDDA
	RETURN
END
select * from  BAOCAONGANTATCA()